version: '3.9'

services:

 crdb:
   image: cockroachdb/cockroach:v22.1.12
   ports:
     - "5433:26257"
     - "8080:8080"
   command: start-single-node --insecure 
   volumes:
     - "${PWD}/test_output/cockroach-data:/cockroach/cockroach-data"
