app = "my-tfc-bb"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[services]]
  internal_port = 3000
  protocol = "tcp"
  processes = ["app"]
  http_checks = []
  script_checks = []

  [services.concurrency]
    hard_limit = 250
    soft_limit = 200

  [[services.ports]]
    handlers = ["tls"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

  [services.ports.tls_options]
    alpn = ["h2"]

[env]
  SERVICE_NAME = "my-tfc-bb"
