name: Backend Deploy

on:
  workflow_call:
    
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs: 
  test:
    uses: ./.github/workflows/backend/backend-test.yaml
    with:
      skip: false

  deploy:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy
