# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build do
    build_app(scheme: "My TFC BB - production", skip_archive: true)
  end

  lane :build_for_testflight do
    increment_build_number(xcodeproj: "My TFC BB.xcodeproj")
    build_app(scheme: "My TFC BB - production")
  end

  lane :internal_testers do
    build_for_testflight
    upload_to_testflight(groups: "Testers")
  end

  lane :external_testers do
    build_for_testflight
    upload_to_testflight(groups: "External Testers")
  end
end
