# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

certificate_ids = [
  "dev.kylejs.My-TFC-BB", 
  "dev.kylejs.My-TFC-BB.My-TFC-BB-Widget"
]

platform :ios do
  lane :build do
    build_app(
      scheme: "My TFC BB - production",
      skip_archive: true,
      skip_package_ipa: true,
      skip_codesigning: true
    )
  end

  lane :renew_certs do
    match(type: "development", app_identifier: certificate_ids)
    match(type: "appstore", app_identifier: certificate_ids)
  end

  lane :certs do
    match(
      type: "appstore",
      app_identifier: certificate_ids,
      readonly: true
    )
  end

  lane :build_for_testflight do
    asc_key
    certs
    increment_build_number(xcodeproj: "My TFC BB.xcodeproj")
    build_app(scheme: "My TFC BB - production")
  end

  lane :asc_key do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY"],
      is_key_content_base64: false,
      in_house: false # detecting this via ASC private key not currently supported
   )
  end

  lane :internal_testers do
    build_for_testflight
    upload_to_testflight(groups: "Testers")
  end

  lane :external_testers do
    build_for_testflight
    upload_to_testflight(groups: "External Testers")
  end
end
