name: Backend Test

on:
  workflow_call:

jobs:
  check-paths: 
    runs-on: ubuntu-latest
    steps:
      - uses: ky1ejs/check-diff-paths-action@v0.1.0
        with:
          paths: |-
            backend/**
            .github/workflows/**
          github-token: ${{ secrets.GITHUB_TOKEN }}

  eslint:
    runs-on: ubuntu-latest
    needs: check-paths
    if: ${{ needs.check-paths.outputs.has-changes }}
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:ci

  buf-lint:
    runs-on: ubuntu-latest
    needs: check-paths
    if: ${{ needs.check-paths.outputs.has-changes }}
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Install buf
        uses: bufbuild/buf-setup-action@v1.10.0
        with:
          github_token: ${{ github.token }}
      - name: Lint protos
        run: buf lint proto

  run-tests:
    runs-on: ubuntu-latest
    needs: check-paths
    if: ${{ needs.check-paths.outputs.has-changes }}
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Boot CockroachDB # getting this done early so it's ready in time
        run: npm run docker:up
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Install buf
        uses: bufbuild/buf-setup-action@v1.10.0
        with:
          github_token: ${{ github.token }}
      - name: Generate protos
        run: npm run proto:gen
      - name: Test
        run: npm test
