name: Backend CI

on:
  push:
    branches: [ main ]
    paths: 
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'backend/**'

jobs:
  eslint:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint:ci

  test:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./backend/package-lock.json
      - name: Boot CockroachDB
        run: npm run docker:up 
      - name: Install buf
        uses: bufbuild/buf-setup-action@v1.10.0
      - name: Generate protos
        run: npm run proto:gen
      - name: Test
        run: npm test
