name: Backend Deploy

on:
  push:
    branches: [ main ]
    paths: 
      - 'backend/**'
      - '.github/workflows/**'

jobs: 
  test:
    uses: ./.github/workflows/backend-test.yaml
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
