name: Backend Deploy

on:
  push:
    branches: [ main ]
    paths: 
      - 'backend/**'
      - '.github/workflows/**'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs: 
  test:
    uses: ./.github/workflows/backend-test.yaml
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
        run: flyctl deploy
