name: Beta Push

on:
  push:
    branches: [ beta ]

jobs:
  check-changed-platforms:
    uses: ./.github/workflows/check-changed-platforms.yaml

  deploy-ios:
    needs: check-changed-platforms
    if: needs.check-changed-platforms.outputs.skip-ios == 'false'
    uses: ./.github/workflows/ios-build.yaml
    secrets: inherit
    with:
      skip: false
      deploy: true
      audience: beta
