name: iOS Build

on:
  workflow_call:
    inputs:
      skip: 
        type: boolean
        required: true
      # ugly way of reusing env prep for iOS. In the long term may make a composite action for this
      # See here for a great breakdown of reusing steps:
      #   https://stackoverflow.com/questions/59757355/reuse-portion-of-github-action-across-jobs/71570847#71570847
      # The downside doing it like this is that deploy shows up as a test action in GitHub statuses and it probably
      # hinders reusability.
      deploy: 
        type: boolean
        required: true
        default: false

env:
  MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

jobs:
 build:
   runs-on: macos-13
   if: ${{ inputs.skip == false }}
   defaults:
      run:
        working-directory: ./ios
   steps:
     - uses: actions/checkout@v2
       with:
        lfs: true

     - name: "Set Xcode Version"
       run: |
         sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer/
         sudo xcode-select -p

     - name: Write Appfile
       run: echo "${{ vars.FASTLANE_APPFILE }}" >> ./fastlane/Appfile

     - name: Install buf
       uses: bufbuild/buf-setup-action@v1.10.0
       with:
         github_token: ${{ github.token }}

     - name: Code gen
       run: |
         brew install swift-protobuf
         brew install grpc-swift
         buf generate ../backend/proto
    
     - name: Test
       if: ${{ !inputs.deploy }}
       run: fastlane build

     - name: Build and upload
       if: ${{ inputs.deploy }}
       run: fastlane internal_testers
