name: iOS PR

on:
  pull_request:
    branches: [ main ]

jobs:
 test:
   runs-on: macos-latest
   defaults:
      run:
        working-directory: ./ios
   steps:
     - uses: actions/checkout@v2

     - name: Write Appfile
       run: echo $FASTLANE_APPFILE >> ./fastlane/Appfile
 
     - name: Set up ruby env
       uses: ruby/setup-ruby@v1.138.0
       with:
         ruby-version: 3.2.1
         bundler-cache: true

     - name: Install fastlane
       run: bundle install

     - name: Install buf
       uses: bufbuild/buf-setup-action@v1.10.0
       with:
         github_token: ${{ github.token }}

     - name: Code gen
       run: |
         brew install swift-protobuf
         brew install grpc-swift
         buf generate ../backend/proto
    
     - name: Build & upload iOS binary
       run: bundle exec fastlane build
