name: Main Push

on:
  push:
    branches: [ main ]

jobs:
  check-changed-platforms:
    uses: ./.github/workflows/check-changed-platforms.yaml
  
  deploy-backend:
    needs: check-changed-platforms
    if: needs.check-changed-platforms.outputs.skip-backend == 'false'
    uses: ./.github/workflows/backend-deploy.yaml
    secrets: inherit

  deploy-ios:
    needs: check-changed-platforms
    if: needs.check-changed-platforms.outputs.skip-ios == 'false'
    uses: ./.github/workflows/ios-build.yaml
    with:
      skip: false
      deploy: true
