name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  check-changed-platforms:
    uses: ./.github/workflows/check-changed-platforms.yaml
  
  backend-test:
    needs: [check-changed-platforms]
    uses: ./.github/workflows/backend-test.yaml
    with:
      skip: ${{ needs.check-changed-platforms.outputs.skip-backend == 'true' }}

  ios-test:
    needs: [check-changed-platforms]
    uses: ./.github/workflows/ios-build.yaml
    with:
      skip: ${{ needs.check-changed-platforms.outputs.skip-ios == 'true' }}
      deploy: true
